spring:
  cloud:
    stream:
      bindings:
        output:
          destination: schedule
          producer:
            requiredGroups: flight-ops
      function:
        definition: generateSchedule
