spring:
  cloud:
    streamapp:
      security:
        enabled: false
    stream:
      bindings:
        output:
          destination: schedule
          producer:
            requiredGroups: flight-ops
      function:
        definition: generateSchedule
  application:
    name: flight-schedule
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8080
